server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ENC(0GMUCNq2if/XKzVsw75X4GcR/4jAOJIF9Ltz1mW34FBMAeCQ8ZlvGtKQyc1GSfEBgK9iouthww7oC/rc1MUSp4nl1M7+j/jE)
          username: ENC(DPXOWw+/Ziwroo1Z/I8oxf4gnwm4clTkIBdU9a59hTA=)
          password: ENC(ndFCwZscxqGeZjxZpJRxhfGK2OtP59/q2U2avbFi0k4ecS5edpWi8oteQy1MKBUxfnDyEyLqRWk=)
          native:
            search-locations: ENC(m9epUMDTBrK6orjujmPmTW2XipKPXRxyLcacVGXZU9m65hrn7kAgQ8KHjBejNRgO5ho3rc5rMA504FoGLpUUlA==)
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: ENC(Bot/+r1iGvPV4zwpaLRlUA==)
    password: ENC(jGrJa8prAIJHNmGjQGmOmhy+wmmvnnRT)

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          - beans
          - httptrace
          - busrefresh

jasypt:
  encryptor:
    bean: jasyptStringEncryptor