server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ENC(KhMHcUbp0YrnIDBNg+es4mfhWbPpr2m3YGOyv7WuejdL5rukP4urB/4zEmJcxJNe6qlT8JXpWiova9/Ed0M4rA==)
          username: ENC(DPXOWw+/Ziwroo1Z/I8oxf4gnwm4clTkIBdU9a59hTA=)
          password: ENC(ndFCwZscxqGeZjxZpJRxhfGK2OtP59/q2U2avbFi0k4ecS5edpWi8oteQy1MKBUxfnDyEyLqRWk=)
          native:
            search-locations: ENC(m9epUMDTBrK6orjujmPmTW2XipKPXRxyLcacVGXZU9m65hrn7kAgQ8KHjBejNRgO5ho3rc5rMA504FoGLpUUlA==)
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          - beans
          - httptrace
          - busrefresh

jasypt:
  encryptor:
    bean: jasyptStringEncryptor